pkg-name:         mariadb_55
display-name:     "MariaDB"
use_cmake:        1
builtin_plugins:  partition,csv,heap,aria,pbxt,myisam,myisammrg,xtradb
pkg-version:      "5.5.22"
srv-version:      "5.5.22"
url:              "http://www.mariab.org"
source:           "mariadb-%{version}.tar.bz2"
src-dir:          "mariadb-%{version}"
lib-version:      18
lib-name:         mariadb55client
description:      'MariaDB is a backward compatible, drop-in replacement branch of the MySQL

Database Server. It includes all major open source storage engines, including

the Maria storage engine.'
---
