---
pkg-name:         mysql-cluster
display-name:     "MySQL Cluster"
preferred:        0
use_cmake:        0
cluster:          1
builtin_plugins:  partition,csv,heap,myisam,innobase,ndbcluster
pkg-version:      "7.1.17"
srv-version:      "5.1.56"
url:              "http://www.mysql.com"
source:           "mysql-cluster-gpl-%{version}.tar.bz2"
src-dir:          "mysql-cluster-gpl-%{version}"
lib-version:      16
lib-name:         mysqlcluster
description:      'SQL is the most popular database language in the world. MySQL is a

client/server implementation that consists of a server daemon (mysqld)

and many different client programs and libraries.


MySQL Cluster is the industry’s only true real-time database that combines the

flexibility of a high availability relational database with the low Total Cost

of Ownership (TCO) of open source. It features a “shared-nothing” distributed

architecture with no single point of failure to assure 99.999% availability,

allowing you to meet your most demanding mission-critical application

requirements.


The official way to pronounce MySQL is "My Ess Que Ell" (Not

MY-SEQUEL).'
---
