pkg-name:         mariadb
display-name:     "MariaDB"
use_cmake:        1
prefered:         1
use_extra_provides: 1
extra_provides:   mariadb_55
builtin_plugins:  partition,csv,heap,aria,pbxt,myisam,myisammrg,xtradb
pkg-version:      "5.5.31"
srv-version:      "5.5.31"
url:              "http://www.mariab.org"
source:           "mariadb-%{version}.tar.bz2"
src-dir:          "mariadb-%{version}"
lib-version:      18
lib-name:         mysqlclient
description:      'MariaDB is a backward compatible, drop-in replacement branch of the MySQL

Database Server. It includes all major open source storage engines, including

the Maria storage engine.'
---
